<?php
session_start();
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<h3>Bitte Instrument w&auml;hlen:</h3>
<table>
<?php

echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-m&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="planet.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-m&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Klasse M planet</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-l&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="lava.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-l&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">LAVA planet</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-i&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="eisplanet.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-i&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Eisplanet</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-z&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="wuste.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-z&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Wuestenplanet</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-lm&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="lmond.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-lm&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">L-Mond</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-om&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="omond.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-om&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">O-Mond</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-mm&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="mmond.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-mm&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">M-Mond</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-gasi&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="gasi.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-gasi&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Gas I</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-gasj&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="gasj.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-gasj&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Gas J</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-gass&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="gass.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=P-gass&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Gas S</font></a></td></tr>';
echo '<hr />';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b1&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="blau1.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b1&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">blauer Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b2&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="blau2.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b2&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">blauer Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b3&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="blau3.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b3&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">blauer Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b4&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="blau4.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b4&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">blauer Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-blau&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="blau.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-blau&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">blauer Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-bs&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="blaustell.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-bs&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">blaue stellare Materie</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r1&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="rot1.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r1&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">roter Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r2&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="rot2.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r2&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">roter Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r3&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="rot3.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r3&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">roter Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r4&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="rot4.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-r4&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">roter Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-rs&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="rotstell.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-rs&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">rote stellare Materie</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-rot&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="rot.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-rot&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">roter Stern</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-gelb&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="gelb.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-gelb&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">GELB</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-orange&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="orange.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-orange&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">ORANGE</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-weiss&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="weiss.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-weiss&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">WEISS</font></a></td></tr>';
echo '<hr />';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-d&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="deut.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-d&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">grosser Deutnebel, Einflug 3x, Sammeln 10 pro 1E</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-dk&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="deutklein.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-dk&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">kleiner Deutnebel, Einflug 2x, Sammeln 5 pro 1E</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-e&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="erz.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-e&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">kleines Erzfeld, Einflug 3x, Sammeln 8 pro 1E</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-ek&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="erzklein.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-ek&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">grosses Erzfeld, Einflug 2x, Sammeln 4 pro 1E</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-x&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="schwarzesloch.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-x&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">schwarzes Loch - Einflug IMMER tot</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="nebel.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-b&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Ceru Nebel, 2 Hullschaden pro Tick, kein beamen fighten schild</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-g&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="green.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-g&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">meta nebel - 10% schilde pro tick ( von maxschilden )</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-p&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="pulsar.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-p&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">gravi riss - tot ohne schilde sonst nix</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-radio&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="nebelgelb.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-radio&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">radioaktiver Nebel - bei einflug mit schilde 2% der hülle, ohne schilde 50% der hülle ,   pro tick wie einflug </font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-metrion&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="metrion.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-metrion&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Metrion -  beim einflug 10E verlust , pro tick 2 E</font></a></td></tr>';
echo '<tr><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-lim&x=',$_GET["x"],'&y=',$_GET["y"],'"><img src="limes.jpg" border="0" /></a></td><td><a href="editsystem.php?system=',$_GET["system"],'&pinsel=W-lim&x=',$_GET["x"],'&y=',$_GET["y"],'"><font color="yellow">Begrenzungsnebel</font></a></td></tr>';
?>
</table>
</body>
</html>