<?php
include_once("connect.php");
mysqli_query($verbindung, "DELETE FROM schiffe WHERE besitzer=4 AND y<20");
mysqli_query($verbindung, "INSERT INTO `d00704ed`.`schiffe` (
`id` ,
`name` ,
`x` ,
`y` ,
`orbit` ,
`besitzer` ,
`energie` ,
`maxenergie` ,
`energieoutput` ,
`laser` ,
`lrs` ,
`hull` ,
`maxhull` ,
`schilde` ,
`maxschilde` ,
`schildstatus` ,
`img` ,
`alarmstufe` ,
`typ` ,
`rohstoffa` ,
`rohstoffb` ,
`rohstoffc` ,
`rohstoffd` ,
`deuterium` ,
`lager` ,
`skillenergie` ,
`skillbau` ,
`skillerz` ,
`flotte` ,
`klasse` ,
`skillbase` ,
`skilldeut`
)
VALUES (
NULL , 'Eskorte1', '10', '11', '', '4', '100', '100', '10', '40', '1', '400', '400', '200', '200', '1', 'fregatte.gif', 'red', 's', '0', '0', '0', '0', '100', '100', '1', '0', '0', '0', 'Fregatte', '0', '0'
)");
mysqli_query($verbindung, "INSERT INTO `d00704ed`.`schiffe` (
`id` ,
`name` ,
`x` ,
`y` ,
`orbit` ,
`besitzer` ,
`energie` ,
`maxenergie` ,
`energieoutput` ,
`laser` ,
`lrs` ,
`hull` ,
`maxhull` ,
`schilde` ,
`maxschilde` ,
`schildstatus` ,
`img` ,
`alarmstufe` ,
`typ` ,
`rohstoffa` ,
`rohstoffb` ,
`rohstoffc` ,
`rohstoffd` ,
`deuterium` ,
`lager` ,
`skillenergie` ,
`skillbau` ,
`skillerz` ,
`flotte` ,
`klasse` ,
`skillbase` ,
`skilldeut`
)
VALUES (
NULL , 'Eskorte1', '10', '11', '', '4', '100', '100', '10', '40', '1', '400', '400', '200', '200', '1', 'fregatte.gif', 'red', 's', '0', '0', '0', '0', '100', '100', '1', '0', '0', '0', 'Fregatte', '0', '0'
)");
mysqli_query($verbindung, "INSERT INTO `d00704ed`.`schiffe` (
`id` ,
`name` ,
`x` ,
`y` ,
`orbit` ,
`besitzer` ,
`energie` ,
`maxenergie` ,
`energieoutput` ,
`laser` ,
`lrs` ,
`hull` ,
`maxhull` ,
`schilde` ,
`maxschilde` ,
`schildstatus` ,
`img` ,
`alarmstufe` ,
`typ` ,
`rohstoffa` ,
`rohstoffb` ,
`rohstoffc` ,
`rohstoffd` ,
`deuterium` ,
`lager` ,
`skillenergie` ,
`skillbau` ,
`skillerz` ,
`flotte` ,
`klasse` ,
`skillbase` ,
`skilldeut`
)
VALUES (
NULL , 'Eskorte1', '10', '11', '', '4', '100', '100', '10', '40', '1', '400', '400', '200', '200', '1', 'fregatte.gif', 'red', 's', '0', '0', '0', '0', '100', '100', '1', '0', '0', '0', 'Fregatte', '0', '0'
)");
mysqli_query($verbindung, "INSERT INTO `d00704ed`.`schiffe` (
`id` ,
`name` ,
`x` ,
`y` ,
`orbit` ,
`besitzer` ,
`energie` ,
`maxenergie` ,
`energieoutput` ,
`laser` ,
`lrs` ,
`hull` ,
`maxhull` ,
`schilde` ,
`maxschilde` ,
`schildstatus` ,
`img` ,
`alarmstufe` ,
`typ` ,
`rohstoffa` ,
`rohstoffb` ,
`rohstoffc` ,
`rohstoffd` ,
`deuterium` ,
`lager` ,
`skillenergie` ,
`skillbau` ,
`skillerz` ,
`flotte` ,
`klasse` ,
`skillbase` ,
`skilldeut`
)
VALUES (
NULL , 'Eskorte1', '10', '11', '', '4', '100', '100', '10', '40', '1', '400', '400', '200', '200', '1', 'fregatte.gif', 'red', 's', '0', '0', '0', '0', '100', '100', '1', '0', '0', '0', 'Fregatte', '0', '0'
)");
mysqli_query($verbindung, "INSERT INTO `d00704ed`.`schiffe` (
`id` ,
`name` ,
`x` ,
`y` ,
`orbit` ,
`besitzer` ,
`energie` ,
`maxenergie` ,
`energieoutput` ,
`laser` ,
`lrs` ,
`hull` ,
`maxhull` ,
`schilde` ,
`maxschilde` ,
`schildstatus` ,
`img` ,
`alarmstufe` ,
`typ` ,
`rohstoffa` ,
`rohstoffb` ,
`rohstoffc` ,
`rohstoffd` ,
`deuterium` ,
`lager` ,
`skillenergie` ,
`skillbau` ,
`skillerz` ,
`flotte` ,
`klasse` ,
`skillbase` ,
`skilldeut`
)
VALUES (
NULL , 'Eskorte1', '10', '11', '', '4', '100', '100', '10', '40', '1', '400', '400', '200', '200', '1', 'fregatte.gif', 'red', 's', '0', '0', '0', '0', '100', '100', '1', '0', '0', '0', 'Fregatte', '0', '0'
)");
mysqli_query($verbindung, "INSERT INTO `d00704ed`.`schiffe` (
`id` ,
`name` ,
`x` ,
`y` ,
`orbit` ,
`besitzer` ,
`energie` ,
`maxenergie` ,
`energieoutput` ,
`laser` ,
`lrs` ,
`hull` ,
`maxhull` ,
`schilde` ,
`maxschilde` ,
`schildstatus` ,
`img` ,
`alarmstufe` ,
`typ` ,
`rohstoffa` ,
`rohstoffb` ,
`rohstoffc` ,
`rohstoffd` ,
`deuterium` ,
`lager` ,
`skillenergie` ,
`skillbau` ,
`skillerz` ,
`flotte` ,
`klasse` ,
`skillbase` ,
`skilldeut`
)
VALUES (
NULL , 'Revenge', '10', '11', '', '4', '100', '100', '10', '100', '1', '4000', '4000', '200', '200', '1', 'mutter.gif', 'red', 's', '0', '0', '0', '0', '100', '100', '1', '0', '0', '0', 'Mutterschiff', '0', '0'
)");


?>
