var bmfertig = "Deine Baumaterialfabrik kostet<br /><font color=\"red\">-5 Energie</font><br />pro Tick und erzeugt:<br />+5 Baustoff";
var weltall = "<b>Weltraum</b>";
var black = "<b>Schwarzes Loch</b><br /><font color='red'>ohne Schilde ist dein Schiff verloren!</font>";
var deut = "<b>dichter Deuteriumnebel</b><br /><font color='green'>10 Deuterium pro Energie<br />mit Tanker einsaugbar</font>";
var deutklein = "<b>d&uuml;nner Deuteriumnebel</b><br /><font color='green'>5 Deuterium pro Energie<br />mit Tanker einsaugbar</font>";
var erz = "<b>dichtes Asteroidenfeld</b><br /><font color='green'>8 Erz pro Energie<br />mit Frachter abbaubar</font>";
var erzklein = "<b>d&uuml;nnes Asteroidenfeld</b><br /><font color='green'>4 Erz pro Energie<br />mit Frachter abbaubar</font>";
var blau = "<b>Saphirnebel</b><br /><font color='red'>Waffen und Sensoren fallen aus</font>";
var radio = "<b>radioaktiver Nebel</b><br /><font color='red'>Warnung: H&uuml;llenschaden</font>";
var metrion = "<b>Metriongasnebel</b><br /><font color='red'>Warnung: Energieverlust</font>";
var green = "<b>Smaragdebel</b><br /><font color='green'>Schilde werden augeladen</font>";
var pulsar = "<b>Subraumverzerrung</b><br /><font color='red'>ohne Schilde ist dein Schiff verloren!</font>";
var stern = "<b>Stern</b><br /><font color='red'>Einflug wird Schiff vernichten!</font>";
var limes = "<b>Limes-Nebel</b><br /><font color='red'>Einflug unm&ouml;glich</font>";
var munbesiedelt = "Klasse M Planet<br /><font color='green'>unbeseidelt</font>"; 
var mbesiedelt = "Klasse M Planet<br /><font color='red'>besiedelt</font>"; 
var lunbesiedelt = "Lavaplanet<br /><font color='green'>unbeseidelt</font>"; 
var lbesiedelt = "Lavaplanet<br /><font color='red'>besiedelt</font>"; 
var iunbesiedelt = "Eisplanet<br /><font color='green'>unbeseidelt</font>"; 
var ibesiedelt = "Eisplanet<br /><font color='red'>besiedelt</font>"; 
var zunbesiedelt = "Wuestenplanet<br /><font color='green'>unbeseidelt</font>"; 
var zbesiedelt = "Wuestenplanet<br /><font color='red'>besiedelt</font>"; 
var sebay = "<b>Schiff</b><br />Klicke auf das Schiff um weitere Informationen<br />zum Schiff zu erhalten oder zu bieten.";
var scanp = "<b>Scannen...</b><br />Scannt den Planeten und zeigt seine Waren an.";
var energ = "<b>Energie transferieren</b><br />Transferiert Energie auf das Ziel.";
var hbeamss = "<b>Beamen</b><br />Du beamst Waren von deinem Schiff auf das Zielschiff.";
var wbeamss = "<b>Beamen</b><br />Du beamst Waren von dem Zielschiff auf dein Schiff.";
var hbeamsp = "<b>Beamen</b><br />Du beamst Waren von deinem Schiff auf den Zielplaneten.";
var wbeamsp = "<b>Beamen</b><br />Du beamst Waren von dem Zielplaneten auf dein Schiff.";
var hbeamps = "<b>Beamen</b><br />Du beamst Waren von deinem Planeten auf das Zielschiff.";
var wbeamps = "<b>Beamen</b><br />Du beamst Waren von dem Zielschiff auf deinen Planeten.";
var hbeampp = "<b>Beamen</b><br />Du beamst Waren von deinem Planeten auf den Zielplaneten.";
var wbeampp = "<b>Beamen</b><br />Du beamst Waren von dem Zielplaneten auf deinen Planeten.";
var nix = "<b>nicht verf&uuml;gbar</b>";
var phaser = "<b>Feuern</b><br />Du greifst das Schiff an.";
var phaserp = "<b>Feuern</b><br />Du greifst den Planeten an.";
var heimatp = "<b><font color='red'>Du kannst diesen Planeten nicht angreifen, da es sich um einen Heimatplaneten handelt.</font></b>";
var scan = "<b>Scannen...</b><br />Scannt das Schiff und zeigt seine Waren an.";
var botschaft = "<b>Botschaft</b><br />Du rufst die Botschaft dieses Objekts ab</b>";
var mail = "<b>Nachricht</b><br />Du sendest dem Besitzer dieses Schiffes eine Nachricht.";
var baustoffonline = "<b>Baustofffabrik - <font color='green'>aktiviert</font></b>";
var duraniumonline = "<b>Duraniumanlage - <font color='green'>aktiviert</font></b>";
var mineonline = "<b>Mine - <font color='green'>aktiviert</font></b>";
var dilimineonline = "<b>Dilithiummine - <font color='green'>aktiviert</font></b>";
var tritaniumonline = "<b>Tritaniumanlage - <font color='green'>aktiviert</font></b>";
var forschungonline = "<b>Forschungsstation - <font color='green'>aktiviert</font></b>";
var antimaterieonline = "<b>Teilchenbeschleuniger - <font color='green'>aktiviert</font></b>";
var soriumonline = "<b>Soriummine - <font color='green'>aktiviert</font></b>";
var fusiononline = "<b>Fusionsreaktor - <font color='green'>aktiviert</font></b>";
var baustoffoffline = "<b>Baustofffabrik - <font color='red'>deaktiviert</font></b>";
var duraniumoffline = "<b>Duraniumanlage - <font color='red'>deaktiviert</font></b>";
var mineoffline = "<b>Mine - <font color='red'>deaktiviert</font></b>";
var dilimineoffline = "<b>Dilithiummine - <font color='red'>deaktiviert</font></b>";
var tritaniumoffline = "<b>Tritaniumanlage - <font color='red'>deaktiviert</font></b>";
var forschungoffline = "<b>Forschungsstation - <font color='red'>deaktiviert</font></b>";
var antimaterieoffline = "<b>Teilchenbeschleuniger - <font color='red'>deaktiviert</font></b>";
var soriumoffline = "<b>Soriummine - <font color='red'>deaktiviert</font></b>";
var fusionoffline = "<b>Fusionsreaktor - <font color='red'>deaktiviert</font></b>";
var lageronline = "<b>Lager - <font color='green'>aktiviert</font></b>";
var schildeonline = "<b>Schildturm - <font color='green'>aktiviert</font></b>";
var werftonline = "<b>Werft - <font color='green'>aktiviert</font></b>";
var plasmaonline = "<b>Plasmakannone - <font color='green'>aktiviert</font></b>";
var solaronline = "<b>Solaranlage - <font color='green'>aktiviert</font></b>";
var wasseronline = "<b>Wasserkraftwerk - <font color='green'>aktiviert</font></b>";
var solaroffline = "<b>Solaranlage - <font color='red'>deaktiviert</font></b>";
var wasseroffline = "<b>Wasserkraftwerk - <font color='red'>deaktiviert</font></b>";
var geoonline = "<b>geothermales Kraftwerk - <font color='green'>aktiviert</font></b>";
var geooffline = "<b>geothermales Kraftwerk - <font color='red'>deaktiviert</font></b>";
var torpedoonline = "<b>Torpedofabrik - <font color='green'>aktiviert</font></b>";
var torpedooffline = "<b>Torpedofabrik - <font color='red'>deaktiviert</font></b>";
var doppelonline = "<b>Doppelbeschleuniger - <font color='green'>aktiviert</font></b>";
var doppeloffline = "<b>Doppelbeschleuniger - <font color='red'>deaktiviert</font></b>";
var npconline ="<b>NPC - Geb&auml;ude (stellt NPC Waren her)</b>";
var npcoffline ="<b>NPC - Geb&auml;ude (stellt NPC Waren her)</b>";
var zentraleonline ="<b>Kolonistenzentrale</b>";
var zentraleoffline ="<b>Kolonistenzentrale</b>";
var basisonline ="<b>Kolonistenbasiskuppel</b>";
var basisoffline ="<b>Kolonistenbasiskuppel</b>";
var botschaft = "<b>Botschaft</b><br />Du rufst die Botschaft dieses Objekts ab</b>";
var lavawerkonline = "<b>Lavakraftwerk - <font color='green'>aktiviert</font></b>";
var lavawerkoffline = "<b>Lavakraftwerk - <font color='red'>deaktiviert</font></b>";
var lagerhoehleonline = "<b>Lagerhöhle</b>";
var lagerhoehleoffline = "<b>Lagerhöhle</b>";